### ISSUE TITLE
error: expected top-level entity

### ISSUE THREAD

**Issue by 3upperm2n** [GPUOpen-ProfessionalCompute-Tools/HIP#64]
Hello,
    I am trying to compile monte carlo photon migration in cuda ([mcx](https://github.com/fangq/mcx)) on rocm.  

    I have cleared all the warnings, but am confronted by the following error. 

    Any suggestions?
 
```bash
leiming@lowfreq:~/mcx_no_symbol/src$ /opt/rocm/hip/bin/hipcc -I/opt/rocm/hip/include  -std=c++11  -DUSE_ATOMIC  -DSAVE_DETECTORS -DUSE_CACHEBOX  -DMCX_TARGET_NAME='"Fermi MCX"'  mcx_core.cpp  -o mcx_core.o 
/opt/rocm/hcc-lc/compiler/bin/llvm-as: /tmp/tmp.U4yAIWtXHr/mcx_core-c8f8d4.o.host_redirect.ll:1:1: error: expected top-level entity
/opt/rocm/hcc-lc/compiler/bin/opt: <stdin>:5768:9: error: stored value and pointer type do not match
^
clang-3.5: error: no such file or directory: '/tmp/tmp.U4yAIWtXHr/mcx_core-c8f8d4.o.host_redirect.bc'
clang-3.5: error: no input files
objdump: 'mcx_core.o': No such file
objdump: '/tmp/mcx_core-c8f8d4.o': No such file
ld: cannot find /tmp/mcx_core-c8f8d4.o: No such file or directory
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
Died at /opt/rocm/hip/bin/hipcc line 378.
```

**Comment by whchung** [comment]
@3upperm2n this looks like a bug caused by one of HCC-specific optimization pass. We are working on getting them removed and to be more conformant with standard Clang/LLVM.

Meanwhile, could you help run the following commands, and rebuild your program?
```
export KMDUMPLLVM=1
export KMDUMPISA=1
```
After you rebuild your program, you will find a few `dump.*` files placed in the directory. Could you then share them with us? From your error log the particular file we'll need would be `dump.host_input.ll` and `dump.host_redirect.ll`.

**Comment by adityaatluri** [comment]
Closing  due to inactivity.
