### ISSUE TITLE
What are the requirements for using `shfl` operations on AMD GPU?

### ISSUE THREAD

**Issue by AlexeyAB** [GPUOpen-ProfessionalCompute-Tools/HIP#66]
There are requirements to use `shfl` operations on nVidia GPU: https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/tree/master/samples/2_Cookbook/4_shfl#requirement-for-nvidia

> requirement for nvidia
> 
> please make sure you have a **3.0 or higher compute capable** device in order to use warp shfl operations and add -gencode arch=compute=30, code=sm_30 nvcc flag in the Makefile while using this application.

Also noted that HIP supports `shfl` for 64 wavesize (WARP-size) on AMD: https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/docs/markdown/hip_faq.md#why-use-hip-rather-than-supporting-cuda-directly

> In addition, HIP defines portable mechanisms to query architectural features, and supports a larger **64-bit wavesize** which expands the return type for cross-lane functions like ballot and shuffle from 32-bit ints to 64-bit ints.

But which of AMD GPUs does support functions `shfl`, or does any AMD GPU support `shfl` because on AMD GPU it implemented by using Local-memory without hardware instruction register-to-register?

**Comment by bensander** [comment]
Alexy - all AMD GPUs supported by ROCm support optimized shuffle operations.
You can programmatically query for this with the HIP_ARCH_ features described in the porting guide.  In some cases, ROCM provides instrinsics which are similar to __shfl in functionality but may offer higher performance on AMD. See for example DPP, ds_shuffle, ds_permute.
-ben

**Comment by AlexeyAB** [comment]
@bensander Thank you!

Yes, there are new instructions in **GCN3** such as: Data-Parallel Primitives (DPP), `ds_bpermute` and `ds_permute` which can provide the functionality such as `__shfl()` and even more: http://gpuopen.com/amd-gcn-assembly-cross-lane-operations/

And yes, these instructions use only route of Local memory (LDS 8.6 TB/s), but don't actually use Local memory, this allows to achive ~51.6 TB/s:

> They use LDS hardware to route data between the 64 lanes of a wavefront, but they don’t actually write to an LDS location.

But I can't find anything about `ds_shuffle`, not in gpuopen.com and not in GCN3 Instruction pdf: 
https://github.com/olvaffe/gpu-docs/raw/master/amd-open-gpu-docs/AMD_GCN3_Instruction_Set_Architecture.pdf

What did you mean about `ds_shuffle`?

**Comment by bensander** [comment]
I meant ds_swizzle (rather than shuffle). Seems like you have found the docs on this already.  Dpp is especially powerful when you can use it since an op can read registers of neighboring workitems directly.

On Feb 27, 2017, at 4:10 PM, Alexey <notifications@github.com<mailto:notifications@github.com>> wrote:


@bensander<https://github.com/bensander> Thank you!

Yes, there are new instructions in GCN3 such as: Data-Parallel Primitives (DPP), ds_bpermute and ds_permute which can provide the functionality such as __shfl() and even more: http://gpuopen.com/amd-gcn-assembly-cross-lane-operations/

And yes, these instructions use only route of Local memory (LDS 8.6 TB/s), but don't actually use Local memory, this allows to achive ~51.6 TB/s:

They use LDS hardware to route data between the 64 lanes of a wavefront, but they don’t actually write to an LDS location.

But I can't find anything about ds_shuffle, not in gpuopen.com<http://gpuopen.com> and not in GCN3 Instruction pdf:
https://github.com/olvaffe/gpu-docs/raw/master/amd-open-gpu-docs/AMD_GCN3_Instruction_Set_Architecture.pdf

What did you mean about ds_shuffle?

**Comment by adityaatluri** [comment]
Hi @AlexeyAB 
HIP provides AMD specific functionality for shfl, swzl

https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/developer-preview/include/hip/hcc_detail/hip_runtime.h#L324
